spring:
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver           #数据库驱动
    url: jdbc:mysql://localhost:3306/newdb1230?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC      #指定mysql数据库中的test子库
    username: root                                     #用户名
    password: root
  thymeleaf:
    check-template-location: false

mybatis:
  type-aliases-package: cn.kgc.test.bean
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true  #开启mybatis的字段命名驼峰转换

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql