spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/myschool
mybatis:
  mapper-locations: classpath:mapper/UserMapper.xml #映射文件
  type-aliases-package: cn.kgc.test.bean #实体类
